blank_issues_enabled: false
contact_links:
  - name: Start a Discussion
    url: https://github.com/usdot-jpo-ode/jpo-wzdx/discussions/category_choices
    about: Ask the WZDx community for input on a question or idea you have.